language: go

go:
  - 1.7.1

# let us have speedy Docker-based Travis workers
sudo: false

install:
  # Symlink below is needed for Travis CI to work correctly on personal forks of swarm
  - export TRAVIS_REPO_SLUG=docker
  - mkdir -p $HOME/gopath/src/github.com/docker/swarm
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/docker/swarm/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/docker/swarm
  - ln -s $HOME/gopath/src/github.com/${TRAVIS_REPO_SLUG///swarm/} $HOME/gopath/src/github.com/docker
  - go get github.com/golang/lint/golint
  - go get github.com/GeertJohan/fgt

before_script:
  - cd $HOME/gopath/src/github.com/docker/swarm

script:
  - script/validate-gofmt
  - go vet `go list ./... | grep -v /vendor/`
  - fgt golint ./... | grep -v vendor/ | tee /dev/stderr
  # Lint shell files and make sure they are not space indented.
  - fgt find test/ -type f \( -name "*.sh" -or -name "*.bash" -or -name "*.bats" \) -exec grep -Hn -e "^ " {} \;
  - GOOS=darwin go build
  - GOOS=windows go build
  - GOOS=linux go build
  - go test -v -race `go list ./... | grep -v /vendor/`
